# Códigos

## Base de datos

```{r fb}

shiny::HTML(
  
'
<iframe src="https://docs.google.com/spreadsheets/d/1sfy6XaCAYKqU1siOr9VP_I5wAzRBjjMmdr1nK387J0s/edit?usp=sharing" style="width: 100%; height: 450px" scrolling="no" marginwidth="0" marginheight="0" frameborder="0" vspace="0" hspace="0"></iframe>
'  

)

```

## Cargar paquetes

```{r pkg, eval=FALSE, echo=TRUE}

library(agricolae)
library(fieldbook)
library(gsheet)
library(openxlsx)
library(car)
library(GerminaR)
library(corrplot)
library(FactoMineR)
library(tidyverse)

```

## Diseño experimental

```{r, design, eval=FALSE, echo=TRUE}

# Factorial in Complete Randomize Design

# Seeds (3) .: Tomato, Corn, Beans 
# Temperature (5) .: T15, T20, T25, T30, T35
# Rep .: 5

library(agricolae)

fb <- design.ab(trt = c(3,5), r = 5,design = "crd")
fb$book

# Exportar fieldbook in csv

getwd()
write.csv(x = fb$book, file = "fb.csv")

```

## Importar datos

```{r upld, eval=FALSE, echo=TRUE}

# Import data Google Spreadsheets

url <- "https://docs.google.com/spreadsheets/d/1sfy6XaCAYKqU1siOr9VP_I5wAzRBjjMmdr1nK387J0s/edit#gid=1326844779"
fb <- gsheet2tbl(url)
fb <- as.data.frame(fb)

# Import data Excel

# fb <- read.xlsx(choose.files(), sheet = "MV")

```

## Box plot

```{r bxp, eval=FALSE, echo=TRUE}

# Using Linear Model

bp <- Boxplot( TUBDW  ~ Genotype, fb, las = 3, id.n=Inf ) 
fb$TUBDW[as.numeric(bp)]  <- NA
bp <- Boxplot( TUBDW  ~ Genotype, fb, las = 3, id.n=Inf ) 

```

## ANOVA

```{r anova, eval=FALSE, echo=TRUE}

av <- aov( LA  ~ Treat * Genotype, fb)
summary(av)

```

## Comparación de medias

```{r mc, eval=FALSE, echo=TRUE}

# Student-Newman-Keuls (agricolae)

mc <- SNK.test(av, c("Genotype", "Treat"))
mc$statistics
mc$means
mc$groups

# Tabla de comparacion de medias (GerminaR)

mc <- GerminaR::ger_testcomp(aov = av, comp = c("Genotype", "Treat"), type = "snk")
mc

```

## Bar plot

```{r barp, eval=FALSE, echo=TRUE}

# ggplot2

ggplot(mc, aes(x = Genotype , y =  mean , fill= Treat))+
  geom_bar(position=position_dodge(),colour="black",stat="identity", size=.5)+
  geom_errorbar(aes(ymin= mean - ste , ymax= mean + ste), size=.3,width=.2,position=position_dodge(.9)) +
  ylab("Peso de tuberculo (g)") +
  xlab("Genotype") +
  scale_y_continuous(limits = c(0,80), breaks= 0:50*5) +
  theme_bw()+
  geom_text(aes(label= sg), colour="black" , vjust=1,  hjust= -0.5 , angle = 90, size= 3 , position=position_dodge(.9))

# GerminaR

fplot(data = mc, type = "bar", x = "Genotype", y = "mean", z = "Treat",
      ylab = "Peso de tuberculo (g)", xlab = "Genotipos", lgl = "Tratamiento",
      erb = T, lmt = c(0,80), brk = 10, color = T, sig = "sg")

```


## Line plot

```{r lnp, eval=FALSE, echo=TRUE}

# ggplot2

ggplot(mc, aes(x = Genotype , y = mean, group= Treat, colour= Treat)) +
  geom_line() +
  geom_point(shape=19, size=2)+
  theme_bw()+
  scale_y_continuous(limits = c(0,80), breaks=0:50*5)+
  ylab("Peso de tuberculo (g)") +
  xlab("Genotype")+
  geom_text(aes(label= sg), colour="black" , vjust=0,  hjust= 0 , angle = 90, size= 3 , position=position_dodge(.9))+
  geom_errorbar(aes(ymin= mean - ste , ymax= mean + ste), size=.3,width=.2)

# GerminaR

fplot(data = mc, type = "line", x = "Genotype", y = "mean", z = "Treat", 4,
      ylab = "Peso de tuberculo (g)", xlab = "Genotipos", lgl = "Tratamiento",
      erb = T, lmt = c(0,80), brk = 10, color = T, sig = "sg")

```

## Análisis de correlación

```{r cor, eval=FALSE, echo=TRUE}

# Corroplot

# Correlation Analysis

cr <- correlation(fb[5:16],method = "pearson")
cr$correlation
cr$pvalue

# Correlation Plot

col <- colorRampPalette(c("#1E90FF", "#6495ED","#7FFFD4", "#FFF0F5", "#FFF0F5","#FFD700", "#FF4500", "#DC143C"))

#png(height=1500, width=1500, pointsize=20, file="correlation.png")
cp <- corrplot(corr = cr$correlation, method = "color", type = "upper", tl.col="black", 
               tl.srt=30, tl.cex = 1, addCoef.col = "black", col=col(200), 
               p.mat = cr$pvalue, sig.level = 0.05, insig = "blank", addgrid.col = "black" )
#dev.off()

```

## Análisis de componentes principales

```{r pca, eval=FALSE, echo=TRUE}

# Principal Component Analisys

pca <- PCA(fb[4:18],graph = F, quali.sup = 1)

# PCA plot

#png(height=1000, width=1000, pointsize=20, file="PCA.png")
plot(pca,choix=c("var"),habillage= 1, cex=0.8,shadow=T,autoLab="yes",title = "") # choix=c("ind")
#dev.off()


```


## Datos metereológicos

```{r met, eval=FALSE, echo=TRUE}

# Meteorological data

url <- "https://docs.google.com/spreadsheets/d/1sfy6XaCAYKqU1siOr9VP_I5wAzRBjjMmdr1nK387J0s/edit#gid=225298935"
md <- gsheet2tbl(url)
md <- as.data.frame(md)
md$DATE <- as.Date(md$DATE, format = "%m/%d/%y")
str(md)

ggplot(md, aes(x = DATE, y = Temp)) + 
  geom_point(aes(colour = Temp)) +
  scale_colour_gradient2(low = "blue", mid = "green" , high = "red", midpoint = 31) + 
  geom_smooth() +
  scale_y_continuous(limits = c(20,45), breaks=0:100*5) +
  theme_bw()+
  theme(axis.text.x = element_text(angle = 45, hjust = 0.8))+
  xlab("Date") +  ylab ("Temperature (ºC)")

```

